# Generated by Django 3.2.9 on 2021-12-15 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='sale_data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
